version: '3.9'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
