version: '3.9'

services:

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes:
    - pgsql_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'

volumes:
  pgsql_data:
    driver: local
